# Build configuration for drift code generation
targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true
          generate_connect_constructor: true
